# Generated by Django 6.0.3 on 2026-03-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, choices=[('KING', 'King'), ('QUEEN', 'Queen'), ('POLICE', 'Police'), ('THIEF', 'Thief'), ('CITIZEN', 'Citizen')], max_length=10, null=True),
        ),
    ]
