# Generated by Django 6.0.3 on 2026-03-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
    ]
