# Generated by Django 6.0.3 on 2026-03-17 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_current_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('action_type', models.CharField(choices=[('SUSPECT', 'Suspect'), ('POLICE_GUESS', 'Police Guess'), ('THIEF_TARGET', 'Thief Target')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
                ('target_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='game.player')),
            ],
        ),
    ]
