# Generated by Django 6.0.3 on 2026-03-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_roundaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='round_ended',
            field=models.BooleanField(default=False),
        ),
    ]
